### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/mnt/deezer-downloader/songs'

### ISSUE THREAD

**Issue by ertaletech** [kmille/deezer-downloader#122]
Starting Threadpool
Traceback (most recent call last):
  File "/usr/local/bin/deezer-downloader", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deezer_downloader/cli/runner.py", line 46, in main
    run_backend()
  File "/usr/local/lib/python3.11/site-packages/deezer_downloader/cli/runner.py", line 10, in run_backend
    from deezer_downloader.web.app import app
  File "/usr/local/lib/python3.11/site-packages/deezer_downloader/web/app.py", line 11, in <module>
    from deezer_downloader.web.music_backend import sched
  File "/usr/local/lib/python3.11/site-packages/deezer_downloader/web/music_backend.py", line 24, in <module>
    check_download_dirs_exist()
  File "/usr/local/lib/python3.11/site-packages/deezer_downloader/web/music_backend.py", line 21, in check_download_dirs_exist
    os.makedirs(directory, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/mnt/deezer-downloader/songs'

must be one of the most boring lib ive ever use, shit readme does this even work?

**Comment by kmille** [comment]
It's a permission issue. The user is not able to write files/create directories in /mnt. You can change that directory in the config file are solve it by `sudo chown ....`.
