### ISSUE TITLE
Blowfish - comment

### ISSUE THREAD

**Issue by fweens** [kmille/deezer-downloader#35]
Great code ! Thanks ;-) It's weird since I wanted to try it on my Mac and I add the following error which was fixed by using key.encode() in blowfishDecrypt and adding b before string key = b"g4el58wc0zvf9na1" and so on:
Traceback (most recent call last):
  File "tests.py", line 195, in test_download_song_valid_mp3
    download_song(song, test_song)
  File "/Users/franckweens/Downloads/Deezer/deezer.py", line 353, in download_song
    decryptfile(fh, key, fo)
  File "/Users/franckweens/Downloads/Deezer/deezer.py", line 137, in decryptfile
    data = blowfishDecrypt(data, key)
  File "/Users/franckweens/Downloads/Deezer/deezer.py", line 116, in blowfishDecrypt
    c = Blowfish.new(key, Blowfish.MODE_CBC, iv)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/Blowfish.py", line 146, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/Blowfish.py", line 77, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/usr/local/lib/python3.8/site-packages/Crypto/Util/_raw_api.py", line 243, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

**Comment by kmille** [comment]
That's interesting. I want to move from `pycrypto` to something else (#25). Maybe it works with the `cryptography` module.
I don't have a Mac to debug it but I'm interested in fixing the bug. I will take a look into it this week.

**Comment by fweens** [comment]
OK let me know if I can help ;-)

**Comment by kmille** [comment]
Can you please retest? I moved to pycryptodome and updated the third party modules. Please check that you use pycryptodome==3.9.9

Ah. I just saw that you already provided a solution :smile: 
Can you check the current code of the master branch? I added two .encode() s during the migration to pycryptodome.

**Comment by fweens** [comment]
Yes it's OK now ;-) Thanks

**Comment by kmille** [comment]
cool! Then I will close the issue
