### ISSUE TITLE
Some trouble to start docker container from a NAS

### ISSUE THREAD

**Issue by TheHBF** [kmille/deezer-downloader#83]
Hi,
I tried to start a docker container from a Synology NAS (DS216+) which is up to date.
I obtain the following errors just after start:

[2022-11-19 09:30:38 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2022-11-19 09:30:38 +0000] [11] [INFO] Listening at: http://0.0.0.0:5000 (11)
[2022-11-19 09:30:38 +0000] [11] [INFO] Using worker: sync
[2022-11-19 09:30:38 +0000] [13] [INFO] Booting worker with pid: 13
Starting Threadpool
[2022-11-19 09:30:39 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/deezer/app/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/deezer/app/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/deezer/app/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/deezer/app/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/deezer/app/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/deezer/app/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/deezer/app/venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/deezer/app/app.py", line 10, in <module>
    from music_backend import sched
  File "/opt/deezer/app/music_backend.py", line 24, in <module>
    check_download_dirs_exist()
  File "/opt/deezer/app/music_backend.py", line 21, in check_download_dirs_exist
    os.makedirs(directory, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/deezer-downloader/songs'
[2022-11-19 09:30:39 +0000] [13] [INFO] Worker exiting (pid: 13)
[2022-11-19 09:30:39 +0000] [11] [INFO] Shutting down: Master
[2022-11-19 09:30:39 +0000] [11] [INFO] Reason: Worker failed to boot.

I don't know what I am missing.
I started a docker container on a linux PC without any problem.
Thank you very much for the project!

**Comment by TheHBF** [comment]
My apologize, I didn't see https://github.com/kmille/deezer-downloader/issues/48 before writing my issue.
`chmod 777 the downloads directory on the host` did the job :-)
Thank you!
